## Library imports + importing dataset

In [169]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("IMDb_Dataset_Edited.csv")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Sample of dataset

In [170]:
df.sample(3)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,budget,imdb_id,original_language,original_title,overview,popularity,tagline,production_companies,production_countries,spoken_languages,keywords,release_year,Director,AverageRating,Poster_Link,Certificate,IMDB_Rating,Meta_score,Star1,Star2,Star3,Star4,Writer,Director_of_Photography,Producers,Music_Composer,genres_list,Cast_list,overview_sentiment,all_combined_keywords
63834,999035,Femorg Peony Jam Playtime,0.0,0,Released,1/3/2022,0,0,True,0,NaN,en,Femorg Peony Jam Playtime,NaN,0.6,NaN,Femorg,NaN,NaN,[],2022,"Viet Nguyen, Jamie Travis, Ry Russo-Young, Gan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Mallory Rosenthal, Lauren Oliver",NaN,NaN,NaN,['Unknown'],"['Todd Williams', 'Bonnie Bedelia', 'Moira Kel...",0.000000,[]
25272,679759,Somebody's Dream,0.0,0,Released,1/3/2020,0,4,False,10,NaN,en,Somebody's Dream,A non-narrative visual short film made on 8mm ...,0.6,HOME VIDEO DREAM...,NaN,United States of America,NaN,"['non-narrative', 'short film']",2020,Ninja Thyberg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DÃ©sirÃ©e Nordlund,NaN,NaN,NaN,['Science Fiction'],"['Ardalan Hakimi Fard', 'Leif Edlund']",0.000000,"['tape', 'cassette tape', 'film', 'non-narrati..."
85235,1213365,Air Pressure (A Diary of the Sky),0.0,0,Released,3/11/2022,0,45,False,0,NaN,en,Air Pressure (A Diary of the Sky),The sky over Lebanon is full of noise. Lawrenc...,0.0,NaN,NaN,NaN,NaN,[],2022,Richard Belfield,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Unknown'],"['Michael Fenner', 'Benjamin Brooks', 'Richard...",0.116667,"['deafening', 'lawrence abu hamdan', 'audiovis..."

# Dataset info with df.info()

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89538 entries, 0 to 89537
Data columns (total 39 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       89538 non-null  int64
 1   title                    89538 non-null  object
 2   vote_average             89538 non-null  float64
 3   vote_count               89538 non-null  int64
 4   status                   89538 non-null  object
 5   release_date             89538 non-null  object
 6   revenue                  89538 non-null  int64
 7   runtime                  89538 non-null  int64
 8   adult                    89538 non-null  bool
 9   budget                   89538 non-null  int64
 10  imdb_id                  40169 non-null  object
 11  original_language        89538 non-null  object
 12  original_title           89538 non-null  object
 13  overview                 85545 non-null  object
 14  popularity               89538 non-null  float64
 15  tagline                  21199 non-null  object
 16  production_companies     39255 non-null  object
 17  production_countries     43045 non-null  object
 18  spoken_languages         45698 non-null  object
 19  keywords                 89538 non-null  object
 20  release_year             89538 non-null  int64
 21  Director                 89538 non-null  object
 22  AverageRating            1118 non-null   float64
 23  Poster_Link              174 non-null    object
 24  Certificate              2566 non-null   object
 25  IMDB_Rating              2596 non-null   float64
 26  Meta_score               145 non-null    float64
 27  Star1                    2596 non-null   object
 28  Star2                    174 non-null    object
 29  Star3                    174 non-null    object
 30  Star4                    174 non-null    object
 31  Writer                   53758 non-null  object
 32  Director_of_Photography  27886 non-null  object
 33  Producers                35010 non-null  object
 34  Music_Composer           12716 non-null  object
 35  genres_list              89538 non-null  object
 36  Cast_list                89538 non-null  object
 37  overview_sentiment       89538 non-null  float64
 38  all_combined_keywords    89538 non-null  object
dtypes: bool(1), float64(6), int64(6), object(26)
memory usage: 26.0+ MB

In [172]:
# Dropping all columns with significant (>50%) amount of null values (with the exception of IMDB rating)
df.drop(columns=["imdb_id","tagline","production_companies","production_countries","spoken_languages","AverageRating","Poster_Link","Certificate","Meta_score","Star1","Star2","Star3","Star4","Director_of_Photography","Producers","Music_Composer"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89538 entries, 0 to 89537
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     89538 non-null  int64
 1   title                  89538 non-null  object
 2   vote_average           89538 non-null  float64
 3   vote_count             89538 non-null  int64
 4   status                 89538 non-null  object
 5   release_date           89538 non-null  object
 6   revenue                89538 non-null  int64
 7   runtime                89538 non-null  int64
 8   adult                  89538 non-null  bool
 9   budget                 89538 non-null  int64
 10  original_language      89538 non-null  object
 11  original_title         89538 non-null  object
 12  overview               85545 non-null  object
 13  popularity             89538 non-null  float64
 14  keywords               89538 non-null  object
 15  release_year           89538 non-null  int64
 16  Director               89538 non-null  object
 17  IMDB_Rating            2596 non-null   float64
 18  Writer                 53758 non-null  object
 19  genres_list            89538 non-null  object
 20  Cast_list              89538 non-null  object
 21  overview_sentiment     89538 non-null  float64
 22  all_combined_keywords  89538 non-null  object
dtypes: bool(1), float64(4), int64(6), object(12)
memory usage: 15.1+ MB

In [173]:
df["IMDB_Rating"].fillna(-1, inplace=True) # fill missing rating valeus with 0
df.fillna("Missing",inplace=True) # Filling all remaining null values with "Missing"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89538 entries, 0 to 89537
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     89538 non-null  int64
 1   title                  89538 non-null  object
 2   vote_average           89538 non-null  float64
 3   vote_count             89538 non-null  int64
 4   status                 89538 non-null  object
 5   release_date           89538 non-null  object
 6   revenue                89538 non-null  int64
 7   runtime                89538 non-null  int64
 8   adult                  89538 non-null  bool
 9   budget                 89538 non-null  int64
 10  original_language      89538 non-null  object
 11  original_title         89538 non-null  object
 12  overview               89538 non-null  object
 13  popularity             89538 non-null  float64
 14  keywords               89538 non-null  object
 15  release_year           89538 non-null  int64
 16  Director               89538 non-null  object
 17  IMDB_Rating            89538 non-null  float64
 18  Writer                 89538 non-null  object
 19  genres_list            89538 non-null  object
 20  Cast_list              89538 non-null  object
 21  overview_sentiment     89538 non-null  float64
 22  all_combined_keywords  89538 non-null  object
dtypes: bool(1), float64(4), int64(6), object(12)
memory usage: 15.1+ MB

In [174]:
df.nunique() # Counting the number of unique values per column

id                       89507
title                    83435
vote_average              2149
vote_count                1041
status                       6
release_date              1826
revenue                   1045
runtime                    429
adult                        2
budget                    1204
original_language            1
original_title           83718
overview                 84208
popularity                7308
keywords                 17012
release_year                 5
Director                 46291
IMDB_Rating                 60
Writer                   39150
genres_list               3138
Cast_list                52126
overview_sentiment       11020
all_combined_keywords    84491
dtype: int64

In [175]:
df.drop_duplicates(inplace=True) # dropping duplicates while considering all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89537 entries, 0 to 89537
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     89537 non-null  int64
 1   title                  89537 non-null  object
 2   vote_average           89537 non-null  float64
 3   vote_count             89537 non-null  int64
 4   status                 89537 non-null  object
 5   release_date           89537 non-null  object
 6   revenue                89537 non-null  int64
 7   runtime                89537 non-null  int64
 8   adult                  89537 non-null  bool
 9   budget                 89537 non-null  int64
 10  original_language      89537 non-null  object
 11  original_title         89537 non-null  object
 12  overview               89537 non-null  object
 13  popularity             89537 non-null  float64
 14  keywords               89537 non-null  object
 15  release_year           89537 non-null  int64
 16  Director               89537 non-null  object
 17  IMDB_Rating            89537 non-null  float64
 18  Writer                 89537 non-null  object
 19  genres_list            89537 non-null  object
 20  Cast_list              89537 non-null  object
 21  overview_sentiment     89537 non-null  float64
 22  all_combined_keywords  89537 non-null  object
dtypes: bool(1), float64(4), int64(6), object(12)
memory usage: 15.8+ MB

In [176]:
# Examining the values found under status and original language
df.value_counts(["status","original_language"])

status           original_language
Released         en                   88545
In Production    en                     578
Post Production  en                     334
Planned          en                      77
Rumored          en                       2
Canceled         en                       1
Name: count, dtype: int64

In [177]:
# Counting number of rows with 0 values for each numerical column
print("Number of entries with vote_average = 0 is ", df[df['vote_average'] == 0]['title'].count())
print("Number of entries with vote_count = 0 is ",  df[df['vote_count'] == 0]['title'].count())
print("Number of entries with revenue = 0 is ", df[df['revenue'] == 0]['title'].count())
print("Number of entries with runtime = 0 is ", df[df['runtime'] == 0]['title'].count())
print("Number of entries with budget = 0 is ", df[df['budget'] == 0]['title'].count())
print("Number of entries with popularity = 0 is ", df[df['popularity'] == 0]['title'].count())

Number of entries with vote_average = 0 is  65299
Number of entries with vote_count = 0 is  65287
Number of entries with revenue = 0 is  87878
Number of entries with runtime = 0 is  11120
Number of entries with budget = 0 is  79745
Number of entries with popularity = 0 is  6606

In [ ]:
df.drop(columns=["vote_average","vote_count","revenue","budget", "keywords","overview_sentiment", "original_title", "all_combined_keywords"], inplace=True) # dropping numerical columns with significant amount of 0 values + keywords, overview_sentiment, original_title because it is unnecessary for this assignment
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89537 entries, 0 to 89537
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              89537 non-null  object
 1   status             89537 non-null  object
 2   release_date       89537 non-null  object
 3   runtime            89537 non-null  int64
 4   adult              89537 non-null  bool
 5   original_language  89537 non-null  object
 6   overview           89537 non-null  object
 7   popularity         89537 non-null  float64
 8   release_year       89537 non-null  int64
 9   Director           89537 non-null  object
 10  IMDB_Rating        89537 non-null  float64
 11  Writer             89537 non-null  object
 12  genres_list        89537 non-null  object
 13  Cast_list          89537 non-null  object
dtypes: bool(1), float64(2), int64(2), object(9)
memory usage: 9.6+ MB

In [179]:
import ast

# Convert string to list with , delimiter
df['Director'] = df['Director'].apply(lambda x: x.split(', '))
df['Writer'] = df['Writer'].apply(lambda x: x.split(', '))

# Convert string representation of lists to actual lists
df['genres_list'] = df['genres_list'].apply(lambda x: ast.literal_eval(x))
df['Cast_list'] = df['Cast_list'].apply(lambda x: ast.literal_eval(x))

In [180]:
# seperating unique genres, actors, directors, writers

director = pd.DataFrame(df['Director'].explode().unique(), columns=["Director"])
writer = pd.DataFrame(df['Writer'].explode().unique(), columns=["Writer"])
genres = pd.DataFrame(df['genres_list'].explode().unique(), columns=["Genre"])
actors = pd.DataFrame(df['Cast_list'].explode().unique(), columns=["Actor Name"])

In [ ]:
# explode the columns with lists, for easier time when converting to SQL database later

MovieDirector = df[["id","title","Director"]].explode("Director")
MovieWriter = df[["id","title","Writer"]].explode("Writer")
MovieGenre = df[["id","title","genres_list"]].explode("genres_list")
MovieActor = df[["id","title","Cast_list"]].explode("Cast_list")

In [ ]:
# Exporting processed dataset with all columns intact
df.to_csv("Processed Dataset.csv", index = False)

# exporting 
director.to_csv("Director", index=False)
writer.to_csv("Writer", index=False)
genres.to_csv("Genre", index=False)
actors.to_csv("Actor", index=False)

MovieDirector.to_csv("MovieDirector", index=False)
MovieWriter.to_csv("MovieWriter", index=False)
MovieGenre.to_csv("MovieGenre", index=False)
MovieActor.to_csv("MovieActor", index=False)